server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379

  # 自定义配置
  mcfw:
    auth:
      noAuthUrls: